// Het oordeel van de criticus per idee, samengevat uit beoordelingen.md.
// Sleutel = het volgnummer van indienen (i1 … i13).
export const VERDICTS = {
  i1: { round: 1, why: 'Tafelstakes: Spotify, Apple, Castbox, Overcast, Pocket Casts, Podcast Addict, Podbean en AntennaPod melden een nieuwe aflevering. Een samengevoegde lijst hebben YouTube Music, Spotify (Following-feed), Castbox, Overcast, Pocket Casts, Podcast Addict en AntennaPod. Het is de herkansing die in de eerste reeks bij "slimme lijsten" werd gevraagd.',
    cond: ['Eén feedronde: de bestaande AutoDownloadWorker (elke 6 uur) doet ook de Nieuw-lijst en de meldingen. Geen tweede taak.', 'ETag en Last-Modified per feed bewaren; FeedClient vraagt nu nog niet voorwaardelijk.', 'Eén definitie van "nieuw": verschenen na het volgen, niet beluisterd en niet weggeveegd. Vegen verbergt, het markeert niet als beluisterd.', 'Geen eigen tabblad: Nieuw staat bovenaan Gevolgd.', 'Eigen meldingskanaal; toestemming pas bij de eerste schakelaar; "alles in de wachtrij" met een grens van 20.'] },
  i2: { round: 1, scope: 'zonder clips', why: 'Bladwijzers hebben YouTube, Overcast, Pocket Casts (betaald, en ze bouwen er nog aan) en Podcast Addict. Clips zijn afgekeurd: Pocket Casts voegde ze in 2024 toe en haalde ze in januari 2025 weer weg omdat de onderliggende bibliotheek ophield. En een link met tijdstip landt nergens, want Toadcast heeft geen webpagina.',
    cond: ['Geen clips. Delen is de bestaande deeltekst plus "vanaf 23:14", zonder link die naar het tijdstip springt.', 'Geen knop in de mediamelding (die heeft er al vijf); alleen in de speler.', 'Zetten is één tik zonder dialoog; de notitie komt achteraf.', 'Geen tabblad: onder de hoofdstukken van de aflevering, en als groep bovenaan Bewaard.', 'Bij elke bladwijzer een kopie van de aflevering, zodat hij blijft werken als de aflevering uit de feed valt.'] },
  i3: { round: 1, why: 'Tafelstakes: alle tien apps casten. AntennaPod alleen in de Play-versie, om dezelfde reden als hier (de Cast-SDK vraagt Play-diensten). De speaker haalt de audio zelf bij de maker; er is geen server nodig.',
    cond: ['Eerst de speler op een echt toestel, dan Media3 bijwerken (nu 1.5.1). In de huidige versie wisselt Media3 zelf tussen telefoon en speaker; dat niet zelf bouwen.', 'Een gedownloade aflevering cast je vanaf de feed-URL. Zonder internet geen cast-knop.', 'Zeggen wat op de speaker niet werkt (inkorten, stemversterking, intro overslaan) en juist testen wat wel moet werken: slaaptimer, hoofdstukken, wachtrij, voortgang.', 'De knop verschijnt alleen als er een Cast-apparaat in het netwerk is.'] },
  i4: { round: 1, why: 'Breed aanwezig: YouTube, Apple ("Recently Played"), Castbox, Pocket Casts, Podcast Addict, Podbean en AntennaPod. En de datalaag moet er toch komen: de Terugblik uit de eerste reeks vraagt geluisterde tijd per dag per show, en die wordt nog niet bijgehouden.',
    cond: ['Eén log voor geschiedenis én Terugblik, met echt geluisterde seconden (spoelen telt niet).', 'De groei begrenzen: samenvoegen per dag per aflevering, of nu naar Room, want LocalStore is één JSON-bestand.', 'Uitzetten en wissen gelden ook voor de Terugblik, en dat staat bij de schakelaar.', 'Geen tabblad: een klokje in de kop van de Bibliotheek.'] },
  i5: { round: 1, scope: 'als "Rond deze sprong"', why: 'Het vult Toadcasts eigen gat: geen van de tien apps toont beweging door de tijd, laat staan wat erbij hoort. De data is er al (feed, tips van de media, historie van de verzamelaar, Apple\'s nieuwe programma\'s). Maar "waarom" belooft een oorzaak, en "nieuwe aflevering" is bij een weekshow bijna altijd waar.',
    cond: ['Kop "Rond deze sprong", neutrale zinnen; de app zegt niet dat het de oorzaak is.', 'Alleen wat hooguit 7 dagen vóór de sprong viel. Een aflevering telt alleen als eerste aflevering, nieuw seizoen of terugkeer na een pauze.', '"Eerst hoog in een ander land" uit de historie van de verzamelaar, met een drempel (top 20 daar, minstens 3 dagen eerder).', 'Per show hooguit één regel, op de grafiek hooguit een handvol stippen.', 'Eerst een maand stijgers in NL en de VS meten. Heeft minder dan een kwart een aanleiding, dan alleen in de chart-tracker.'] },
  i7: { round: 1, scope: 'alleen handmatig', why: 'Bij apps zonder account is dit wat zware luisteraars missen: Podcast Addict en AntennaPod hebben het, en er komen nog verzoeken om meer. OPML bewaart alleen wat je volgt. Maar Android Auto Backup staat al aan, en de hitlijsthistorie is niet onherstelbaar (de verzamelaar bewaart alles). Wat overblijft is verhuizen en de build zonder Google.',
    cond: ['Alleen handmatig exporteren en terugzetten, naast de OPML-import. Geen wekelijkse ronde, geen vraag bij de eerste start.', 'Alleen wat van de gebruiker is: volgen, makers, wachtrij, bewaard, voortgang, bladwijzers, geschiedenis, instellingen. Geen momentopnames of caches.', 'Een versienummer in het bestand. Terugzetten vervangt alles, met vooraf een samenvatting.', 'Eerst testen dat Auto Backup werkt, en het noemen in Instellingen.'] },
  i8: { round: 1, why: 'De slaaptimer is tafelstakes en bestaat al. Deze verfijningen gebruiken slaapluisteraars echt: uitfaden bij Overcast, Podcast Addict, AntennaPod en Pocket Casts; schudden bij Pocket Casts en AntennaPod; een tijdvak bij AntennaPod. Klein en lokaal.',
    cond: ['Uitfaden standaard aan; daarna het volume terug op 100% (die bug had Pocket Casts).', 'Schudden alleen in de laatste minuten van een lopende timer. Zonder sensor of toestemming moet de timer gewoon werken.', 'Terugspoelen bij het hervatten, niet bij het stoppen, en niet na "einde aflevering".', 'Het tijdvak geldt alleen als je zelf op afspelen drukt, en nooit in de auto.', 'Het slaaptimermenu blijft kort: de extra keuzes staan in Instellingen.'] },
  i9: { round: 1, why: 'Apple en Spotify lezen itunes:type. Voor een hitlijstenapp is het een echt gat: in de lijsten staan veel verhalende shows, en afspelen vanuit de lijst begint nu bij de nieuwste aflevering, midden in het verhaal. Dit repareert de kernroute.',
    cond: ['Ook itunes:episodeType lezen: "begin bij 1" slaat trailers en bonussen over.', 'Sorteren op seizoen en afleveringsnummer, met de datum als terugval. Ontbreekt het begin, dan "oudste beschikbare".', 'Dezelfde regel bij afspelen vanuit de hitlijst. De hitlijstradio blijft per aflevering.', 'De volgende in de reeks één tegelijk klaarzetten, en alleen als hij nog niet in de wachtrij staat.', 'Per show om te zetten, voor makers die de tag verkeerd zetten.'] },
  i11: { round: 2, why: 'Bijna alle podcastapps laten de spoelstappen instellen: Apple, Overcast, Pocket Casts, Podcast Addict, AntennaPod, Castbox, Podbean, en YouTube met dubbeltikken. Alleen Spotify zit vast, en daar vragen gebruikers erom. Apple, Overcast, Pocket Casts en AntennaPod laten ook kiezen wat de koptelefoon doet. Weinig werk.',
    cond: ['Standaard spoelt de koptelefoon: nu doet "volgende" op een koptelefoon waarschijnlijk niets, want de speler bevat één aflevering. "Volgende in de wachtrij" wordt een optie.', 'Een ForwardingPlayer met de gekozen stappen, zodat melding, vergrendelscherm en auto hetzelfde getal tonen (ExoPlayer legt ze anders vast bij het bouwen).', 'Volgende, vorige en de knop van de koptelefoon zelf verwerken, en testen op een toestel.', 'De koptelefoonkeuze geldt niet voor de knoppen in Android Auto.', 'Eén algemene instelling, niet per show.'] },
  i13: { round: 3, why: 'Apple, Spotify ("Find in this show"), Overcast, Pocket Casts, Castbox en AntennaPod zoeken binnen één show; YouTube binnen een kanaal. Overcast-gebruikers noemen zoeken in de shownotes een topfunctie. In Toadcast bestaat het nog niet, en het is goedkoop: de feed is al geladen, mét omschrijvingen.',
    cond: ['Zoek in alle afleveringen uit de feed, niet alleen in de 20 zichtbare. Geen eigen sorteerknop: de volgorde komt van de seriële functie.', 'De doorzoekbare tekst één keer klaarmaken buiten de hoofdthread (platte tekst, kleine letters, accenten weg) en filteren na een korte pauze in het typen.', 'Een treffer die alleen in de shownotes zit, krijgt een regel tekst rond het gevonden woord.', 'Altijd zeggen waarin gezocht is ("12 van de 300 afleveringen in de feed"), en alleen waarschuwen voor een ingekort archief als daar een teken van is.', 'Geen treffers: een knop om in heel Toadcast op dezelfde term te zoeken.'] }
};

export const REJECTED = [
  { n: 6, round: 1, title: 'Deelkaart van een notering', why: 'Geen van de tien apps heeft het, en de onderbouwing klopte niet: makers hebben sinds Chartable stopte gratis plekken voor hun notering (Apple\'s lijsten, Podcharts, Ausha Charts). De chart-tracker deelt noteringen al als tekst, en de Terugblik brengt al een deelbare afbeelding.', again: 'Eén optie "als afbeelding" in de bestaande deelknop van de chart-tracker, op de renderer van de Terugblik, in één formaat, ná de Terugblik.' },
  { n: 10, round: 1, title: 'Proefluisteren vanuit de hitlijst', why: 'Alleen Spotify heeft voorproefjes, en dan op Home. Geen van de tien leest podcast:soundbite. "Na minuut 5" is weer een vaste gok, lang drukken voor een minuut werkt niet als bediening, zoeken midden in een mp3 op afstand is traag, en het overlapt met de hitlijstradio.', again: 'Alleen met een fragment dat de maker zelf aanwijst (soundbite of trailer), via een zichtbare knop, en na een meting hoeveel shows in de top 200 er een hebben.' },
  { n: 12, round: 2, title: 'Apple en Spotify naast elkaar', why: 'Luisteraars missen het niet aantoonbaar, en de bewering over wat Apple en Spotify meten was te stellig. De lijsten passen slecht: Spotify heeft per categorie een top 50 in een deel van de landen, mist categorieën en heeft geen afleveringen per categorie. Koppelen kost vijftig zoekverzoeken per scherm, en per show staan beide bronnen al naast elkaar.', again: 'Een klein label in de bestaande lijst ("ook #11 bij Spotify"), met de koppeling uit de verzamelaar, alleen waar beide bronnen dezelfde lijst hebben.' }
];
