// Het oordeel van de criticus per idee, samengevat uit beoordelingen.md.
export const VERDICTS = {
  f1: { round: 1, ok: true, why: 'Alle tien apps uit het onderzoek hebben het, en het is Toadcasts grootste achterstand. 61% streamt of downloadt pas vlak voor het luisteren, dus "de nieuwste N" is beter dan een hele achterstand binnenhalen. Media3 doet het op het toestel.',
    cond: ['Automatisch downloaden staat standaard uit, of op 1.', 'Bewaard en in de wachtrij wordt nooit automatisch gewist.', 'Wifi- en oplaadregels via Media3 of WorkManager, niet zelf controleren.', 'Test feeds met doorverwijzingen en meetvoorvoegsels (OP3, Podtrac).'] },
  f2: { round: 1, ok: true, why: 'Zeven van de tien apps hebben hoofdstukken, en "einde van dit hoofdstuk" is een fijne slaaptimer. De dekking is laag: ongeveer 0,9% van de afleveringen heeft podcast:chapters in de feed.',
    cond: ['Lees ook Podlove Simple Chapters (psc:chapters), die veel Nederlandse en Duitse makers gebruiken.', 'Zonder hoofdstukken toont de speler niets: geen lege lijst, geen streepjes.', 'Vorige en volgende blijven over de wachtrij gaan. Springen gaat via de lijst.', 'Voor de lijst vóór het afspelen: het begin van het mp3-bestand ophalen met een range-verzoek.'] },
  f3: { round: 1, ok: true, why: 'Transcripties zijn standaard geworden bij Apple, Spotify, Pocket Casts, Overcast en Amazon, en het ontwerp klopt: meelezen, tikken om te springen, zoeken, en niet zelf transcriberen. Maar de grote apps maken hun tekst met AI; uit de RSS komt maar ongeveer 4%.',
    cond: ['Harde voorwaarde: laat de verzamelaar eerst tellen hoeveel afleveringen in de top 200 van NL en US een transcript hebben. Onder ongeveer 10% pas bouwen ná downloaden, hoofdstukken, inkorten en OPML.', 'Het tabblad Tekst verschijnt alleen als er tekst is.', 'SRT, VTT en JSON. HTML zonder tijden als platte tekst, zonder meelopen.'] },
  f4: { round: 1, ok: true, why: 'Het meest onderscheidende luisterkenmerk uit het onderzoek. Overcast bouwde er zijn naam op, en YouTube en Apple halen het nu in. Media3 en Android hebben de onderdelen al.',
    cond: ['"Bespaard" is echt gemeten: de overgeslagen frames optellen, niet schatten.', 'Stemversterking voorzichtig afstellen, zonder vervorming. Testen op shows met veel muziek.', 'De schakelaars horen in het snelheidsmenu, niet als extra knoppenrij.'] },
  f5: { round: 1, ok: true, why: 'Precies het gat dat Toadcast kan vullen: geen van de tien apps laat zien hoe shows door de tijd bewegen. Het dubbelt de chart-alerts niet; die zijn een dagkaart in de Bibliotheek.',
    cond: ['De weekvergelijking komt uit de historie van de verzamelaar, want de app legt een lijst alleen vast als je hem opent.', 'Een eigen wekelijkse achtergrondtaak.', 'Hooguit drie lijsten, afgeleid uit je bibliotheek en zelf in te stellen.', 'Een eigen meldingskanaal. De dagkaart Chart-alerts blijft.'] },
  f6: { round: 1, ok: true, why: 'Jaaroverzichten zijn geliefd (Spotify Wrapped, Pocket Casts Playback, AntennaPod Echo) en kunnen helemaal op het toestel. "Vroege luisteraar" kan geen concurrent namaken.',
    cond: ['Nu al beginnen met het bijhouden van geluisterde tijd per dag per show; elke week wachten is een week data kwijt.', 'Een volgdatum bij gevolgde shows.', 'De top-20-datum uit de historie van de verzamelaar, met een vaste regel welke lijst telt.', 'Ook per maand, en geen kaart bij een paar uur luisteren. De afbeelding wordt op het toestel gemaakt.'] },
  f7: { round: 1, ok: true, why: 'Alle open apps in de top hebben het, geen enkele gesloten app. Het was de verhuisroute toen Google Podcasts stopte, en voor een app zonder account is het de enige back-up.',
    cond: ['Volgen met alleen een feed-adres mogelijk maken, en later aan Apple koppelen. De import wacht daar niet op.', 'Neem "zelf een feed toevoegen" meteen mee.', 'Bij export apart melden welke shows alleen op Spotify staan.', '"Delen met Toadcast" vanuit een andere app moet werken voor OPML.'] },
  f10: { round: 1, ok: true, why: 'Het verbindt hitlijst en luisteren met één tik, en draait op wat er al is: de afleveringslijsten van de verzamelaar, de wachtrij en de voortgang. De voorgestelde proefmodus (eerste 10 minuten) is afgekeurd: juist die minuten zijn vaak reclame en intro.',
    cond: ['Vraag wat er met de bestaande wachtrij gebeurt.', 'Eén aflevering per show, hooguit tien.', 'Spotify levert shows, geen afleveringen: daar per show de nieuwste aflevering, en dat zichtbaar maken.', 'Proeven later via hoofdstukken of podcast:soundbite.'] },
  f11: { round: 2, ok: true, why: 'Alle tien apps werken in de auto, en daar kun je alleen luisteren. PlaybackService heeft al eigen knoppen voor −15/+30 en snelheid, dus een MediaLibraryService is een uitbreiding. Een hitlijst in de auto heeft geen concurrent.',
    cond: ['Eerst afspelen op een echt toestel testen, daarna de Desktop Head Unit.', 'Hooguit vier tabbladen en een paar eigen knoppen.', 'Hoezen via een eigen ContentProvider.', '"Hey Google, speel [show]" moet werken, anders keurt Google af.', 'Android Automotive komt niet vanzelf mee: dat is een eigen build en keuring.'] },
  f12: { round: 2, ok: true, why: 'Pocket Casts, Podcast Addict, Overcast en AntennaPod hebben het, en zware luisteraars missen het bij overstappen. Alles staat op "zoals algemeen", dus wie het niet opent merkt niets.',
    cond: ['Alleen opties waarvan de basis er is. De schakelaar voor meldingen bij een nieuwe aflevering komt pas als die meldingen bestaan.', 'Intro overslaan alleen bij starten vanaf het begin; outro overslaan telt als beluisterd.', 'Een andere snelheid in de speler past de show-instelling aan, en dat is te zien.', 'Een vaste sleutel per show, ook voor shows die via OPML binnenkwamen.'] }
};

export const REJECTED = [
  { n: 8, title: 'Widget op het beginscherm', why: 'Geen standaard bij de tien apps, en de spelerwidget dubbelt de mediamelding en het vergrendelscherm die Toadcast al heeft. De top-5-widget is wel eigen, maar leunt op een dagelijkse ophaalronde die er niet is.', again: 'Alleen de hitlijstwidget, ververst door de taak van het weekoverzicht, na de basisfuncties.' },
  { n: 9, title: 'Slimme lijsten met regels', why: 'Filters zitten alleen in apps voor zware luisteraars, niet in de grote vijf. Een regelbouwer is veel scherm voor een kleine groep, en het hitlijstfilter overlapt met de Hitlijstradio.', again: 'Eén lijst "Nieuwe afleveringen" van alle gevolgde shows, met drie vaste chips en "alles in de wachtrij".' }
];
